### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by vetalmon20**
I just deleted all data from master branch, created new branch and added all the data to a new branch in order to make a pull request.

### CODE REVIEW

**Review by dt-iss — COMMENTED** [review]
Code should be complemented by documentation strings according to appropriate conventions.
The project structure is ugly. It should be revised and restructured.

**Comment by vetalmon20** [comment]
Restructured my Lab

**Review by dt-iss — DISMISSED** [review]
Add third kind of list implementation, based on vector.
Add user interface.

**Review by dt-iss — COMMENTED** [review]
Add third kind of list implementation, based on vector.
Add user interface.

**Pull request merged**
